// <auto-generated />
using Meshline.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meshline.Storage.Migrations
{
    [DbContext(typeof(MeshlineDbContext))]
    [Migration("20260925135953_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Meshline.Storage.AccountEstablishmentRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelayId")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountEstablishment");
                });

            modelBuilder.Entity("Meshline.Storage.AccountProfileRecord", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerCertificateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("AccountProfiles");
                });

            modelBuilder.Entity("Meshline.Storage.AccountRouteRecord", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("AccountRoutes");
                });

            modelBuilder.Entity("Meshline.Storage.AccountTimelineRecord", b =>
                {
                    b.Property<string>("RelayId")
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasRetentionGap")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSynchronizedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelayId");

                    b.ToTable("AccountTimelines");
                });

            modelBuilder.Entity("Meshline.Storage.ChannelDescriptorRecord", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(27)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId", "Revision");

                    b.ToTable("ChannelDescriptors");
                });

            modelBuilder.Entity("Meshline.Storage.ChannelOperationRecord", b =>
                {
                    b.Property<string>("RelayId")
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RelayId", "ResourceId", "Method");

                    b.ToTable("ChannelOperations");
                });

            modelBuilder.Entity("Meshline.Storage.ChannelPostRecord", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(27)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AcceptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppliedThrough")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostJson")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId", "Sequence");

                    b.HasIndex("ChannelId", "MessageId", "Author");

                    b.ToTable("ChannelPosts");
                });

            modelBuilder.Entity("Meshline.Storage.ChannelRecord", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasMaxLength(27)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptorJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFollowed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelayId")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("SyncSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId");

                    b.HasIndex("IsFollowed", "RelayId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Meshline.Storage.ContactRequestRecord", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SendState")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "Direction");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("Meshline.Storage.ContactStateRecord", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmedGrantToJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantFromJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantToJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RequiredDeviceRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("State", "UpdatedAt");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Meshline.Storage.ConversationReadRecord", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId");

                    b.ToTable("ConversationReads");
                });

            modelBuilder.Entity("Meshline.Storage.DatabaseBinding", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsConcurrencyToken()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseBinding");
                });

            modelBuilder.Entity("Meshline.Storage.DeviceStateRecord", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("DeviceStates");
                });

            modelBuilder.Entity("Meshline.Storage.GroupAccountMessageCursorRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocalSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GroupAccountMessageCursor");
                });

            modelBuilder.Entity("Meshline.Storage.GroupBanRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "AccountId");

                    b.ToTable("GroupBans");
                });

            modelBuilder.Entity("Meshline.Storage.GroupEpochRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Epoch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commitment")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyEntryJson")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MemberPublicKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProtectedApplicationSecret")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProtectedClientSecret")
                        .HasColumnType("BLOB");

                    b.HasKey("GroupId", "Epoch");

                    b.ToTable("GroupEpochs");
                });

            modelBuilder.Entity("Meshline.Storage.GroupEventRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecryptedPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("Epoch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMessage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rejection")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderDeviceId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "Sequence");

                    b.HasIndex("GroupId", "IsMessage", "Sequence");

                    b.ToTable("GroupEvents");
                });

            modelBuilder.Entity("Meshline.Storage.GroupMemberKeyRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedPrivateKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Shared")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "PublicKey");

                    b.ToTable("GroupMemberKeys");
                });

            modelBuilder.Entity("Meshline.Storage.GroupMemberRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("JoinedAtSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<long>("NicknameSequence")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "AccountId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("Meshline.Storage.GroupOperationRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "Method");

                    b.ToTable("GroupOperations");
                });

            modelBuilder.Entity("Meshline.Storage.GroupRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("Commitment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("Epoch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvitePolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocallyClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagementHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("MemberCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemberCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Membership")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelayId")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Meshline.Storage.GroupRotationRecord", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCommitment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commitment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("OwnerPublicKey")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProtectedSecret")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("GroupId");

                    b.ToTable("GroupRotations");
                });

            modelBuilder.Entity("Meshline.Storage.HomeRelayMigrationRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("RouteValiditySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceRelayId")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRelayId")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeRelayMigration");
                });

            modelBuilder.Entity("Meshline.Storage.LocalDeviceRecord", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedEncryptionKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProtectedSigningKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceId");

                    b.ToTable("LocalDevice");
                });

            modelBuilder.Entity("Meshline.Storage.MessageOutboxRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcceptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelayId")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("MessageOutbox");
                });

            modelBuilder.Entity("Meshline.Storage.SignedRequestRecord", b =>
                {
                    b.Property<string>("Method")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelayId")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Method");

                    b.ToTable("SignedRequests");
                });

            modelBuilder.Entity("Meshline.Storage.StoredMessageRecord", b =>
                {
                    b.Property<long>("LocalSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedPayload")
                        .HasColumnType("BLOB");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderDeviceId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT");

                    b.HasKey("LocalSequence");

                    b.HasIndex("IsDirect", "CreatedAt");

                    b.HasIndex("Recipient", "CreatedAt");

                    b.HasIndex("Sender", "MessageId")
                        .IsUnique();

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
