<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Meshline.Tests</RootNamespace>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <ProjectReference Include="../../src/Meshline.Sdk/Meshline.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../../tests/vectors/*.json" Link="TestData/Vectors/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../../tests/scenarios/*.json" Link="TestData/Scenarios/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
